services:
  c2c_server:
    image: whaleflu_c2c
    networks:
      whaleflu_network:
        ipv4_address: 192.168.0.1
    ports:
      - "4000" # C2C server port

  whaleflu_infected:
    image: whaleflu_infected
    networks:
      whaleflu_network:
        ipv4_address: 192.168.0.2
    ports:
      - "4000"
      - "22"

  whaleflu_target_1:
    image: whaleflu_base
    networks:
      whaleflu_network:
        ipv4_address: 192.168.0.3
    ports:
      - "4000"
      - "22"

  whaleflu_target_2:
    image: whaleflu_base
    networks:
      whaleflu_network:
        ipv4_address: 192.168.0.4
    ports:
      - "4000"
      - "22"

networks:
  whaleflu_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/23
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.1
